sudo: required

language: bash

env:
  global:
  - BUILD_NAME=ExampleProjectName

services:- docker

before_install:

- openssl aes-256-cbc -K $encrypted_82766e747237_key -iv 
	$encrypted_82766e747237_iv
  -in ./unity3d.alf -out ./Unity_v2017.x.ulf -d

- export UNITY_LICENSE_CONTENT=`cat Unity_v2017.x.ulf`

- rm Unity_v2017.x.ulf

- docker pull $IMAGE_NAME

jobs:
  include:
  
	- stage: test
    
		script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    
		env: TEST_PLATFORM=editmode IMAGE_NAME=gableroux/unity3d:2019.3.7f1
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: test
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=playmode IMAGE_NAME=gableroux/unity3d:2019.3.7f1
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  
	- stage: build
    
		env: BUILD_TARGET=StandaloneLinux64 IMAGE_NAME=gableroux/unity3d:2019.3.7f1
    script: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "./Builds/"
  - stage: build
    env: BUILD_TARGET=StandaloneOSX IMAGE_NAME=gableroux/unity3d:2019.3.7f1-mac
    script: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "./Builds/"
  
	- stage: build
    
		env: BUILD_TARGET=StandaloneWindows64 IMAGE_NAME=NateUllman/unity3d:2019.3.12f1-windows
    
		script: "chmod +x ./ci/build.sh &&./ci/docker_build.sh"
    
		addons:
      artifacts:
        s3_region: "us-west-1"
        
		paths:
        - "./Builds/"
  
		deploy: provider: releases 
			api_key: e2e1604a8bdc35a260be2a7dec83f1b3f14e9fa6 
			file: StandAloneWinSD.zip
			skip_cleanup: true
	- stage: build
    env: BUILD_TARGET=WebGL IMAGE_NAME=gableroux/unity3d:2019.3.7f1-webgl
    script: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "./Builds/"
